// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPf83FHEfPA4aBEYFzEbNcdW1e5jikZw0',
    appId: '1:698700077984:web:47bdd7505c0f27cc72a2c5',
    messagingSenderId: '698700077984',
    projectId: 'smartgreen-1ab20',
    authDomain: 'smartgreen-1ab20.firebaseapp.com',
    storageBucket: 'smartgreen-1ab20.firebasestorage.app',
    measurementId: 'G-0093HGQP8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1P_JUY35OBRQv9wMC8AguNjnZKkRcq4',
    appId: '1:698700077984:android:07d6f200dcd6b74c72a2c5',
    messagingSenderId: '698700077984',
    projectId: 'smartgreen-1ab20',
    storageBucket: 'smartgreen-1ab20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyrwk_Xji9oArvDHIyy_R6H4JJ0a7dM8',
    appId: '1:698700077984:ios:cc369168fc58fc8e72a2c5',
    messagingSenderId: '698700077984',
    projectId: 'smartgreen-1ab20',
    storageBucket: 'smartgreen-1ab20.firebasestorage.app',
    iosBundleId: 'com.example.smartgreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyrwk_Xji9oArvDHIyy_R6H4JJ0a7dM8',
    appId: '1:698700077984:ios:cc369168fc58fc8e72a2c5',
    messagingSenderId: '698700077984',
    projectId: 'smartgreen-1ab20',
    storageBucket: 'smartgreen-1ab20.firebasestorage.app',
    iosBundleId: 'com.example.smartgreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPf83FHEfPA4aBEYFzEbNcdW1e5jikZw0',
    appId: '1:698700077984:web:06b1ddadd67633fb72a2c5',
    messagingSenderId: '698700077984',
    projectId: 'smartgreen-1ab20',
    authDomain: 'smartgreen-1ab20.firebaseapp.com',
    storageBucket: 'smartgreen-1ab20.firebasestorage.app',
    measurementId: 'G-MV5NYFKNP8',
  );

}